live_config_reload = true

[bell]
animation = "EaseOutExpo"

[font]
size = 11

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "=", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
]
