live_config_reload = true

[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 13

[font.normal]
family = "JetBrains Mono"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 3

[window]
option_as_alt = "Both"
