[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
separator_open = "["
separator_close = "]"

[icon]
globs = []
dirs  = [{ name = "*/", text = "+" }]
files = [{ name = "*", text = " "}]
exts  = []
conds = []

[which]
separator = " > "
