theme = "rasmus-alt"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
rulers = [80, 100, 120]
scrolloff = 20

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
snippets = false

[editor.soft-wrap]
enable = true

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "total-line-numbers",
  "file-encoding"
]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space.b]
b = "buffer_picker"
c = ":buffer-close"
C = ":buffer-close-others"
n = ":new"
r = ":reload"
R = ":reload-all"
