theme = "rasmus-alt"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
rulers = [80, 100, 120]
scrolloff = 20

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "total-line-numbers",
  "file-encoding"
]
