return {
	-- {
	--     "folke/flash.nvim",
	--     event = "VeryLazy",
	--     ---@type Flash.Config
	--     opts = {},
	--     -- stylua: ignore
	--     keys = {
	--         { "s",     mode = { "n", "x", "o" }, function() require("flash").jump() end,              desc = "Flash" },
	--         { "S",     mode = { "n", "x", "o" }, function() require("flash").treesitter() end,        desc = "Flash Treesitter" },
	--         { "r",     mode = "o",               function() require("flash").remote() end,            desc = "Remote Flash" },
	--         { "R",     mode = { "o", "x" },      function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
	--         { "<c-s>", mode = { "c" },           function() require("flash").toggle() end,            desc = "Toggle Flash Search" },
	--         { "*",
	--             function()
	--                 require("flash").jump({
	--                     pattern = vim.fn.expand("<cword>"),
	--                 })
	--             end
	--         },
	--     },
	-- },
	-- {
	-- 	"haya14busa/vim-asterisk",
	-- 	keys = {
	-- 		{
	-- 			"*",
	-- 			[[<Plug>(asterisk-z*)<cmd>lua require('hlslens').start()<cr>]],
	-- 			desc = "Find next word under cursor",
	-- 		},
	-- 		{
	-- 			"#",
	-- 			[[<Plug>(asterisk-z#)<cmd>lua require('hlslens').start()<cr>]],
	-- 			desc = "Find previous word under cursor",
	-- 		},
	-- 		{
	-- 			"g*",
	-- 			[[<Plug>(asterisk-gz*)<cmd>lua require('hlslens').start()<cr>]],
	-- 			desc = "Find next word under cursor",
	-- 		},
	-- 		{
	-- 			"g#",
	-- 			[[<Plug>(asterisk-gz#)<cmd>lua require('hlslens').start()<cr>]],
	-- 			desc = "Find previous word under cursor",
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"kevinhwang91/nvim-hlslens",
	-- 	-- config = function()
	-- 	-- 	require("hlslens").setup()
	-- 	-- 	local kopts = { noremap = true, silent = true }
	-- 	-- 	vim.api.nvim_set_keymap("n", "*", [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
	-- 	-- 	-- vim.api.nvim_set_keymap("n", "#", [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
	-- 	-- 	-- vim.api.nvim_set_keymap("n", "g*", [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
	-- 	-- 	-- vim.api.nvim_set_keymap("n", "g#", [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)
	-- 	-- end,
	-- 	-- keys = {
	-- 	-- 	{
	-- 	-- 		"*",
	-- 	-- 		[[*<Cmd>lua require('hlslens').start()<CR>]],
	-- 	-- 		noremap = true,
	-- 	-- 	},
	-- 	-- 	{
	-- 	-- 		"n",
	-- 	-- 		[[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
	-- 	-- 		noremap = true,
	-- 	-- 	},
	-- 	-- 	{
	-- 	-- 		"N",
	-- 	-- 		[[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
	-- 	-- 		noremap = true,
	-- 	-- 	},
	-- 	-- },
	-- },
}
